### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by BaneWong** [natanfudge/Auto-Using#13]
- Issue Type: `Performance`
- Extension Name: `auto-using`
- Extension Version: `0.7.8`
- OS Version: `Darwin x64 18.6.0`
- VSCode version: `1.35.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/Users/Bo/Fudge.auto-using-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by natanfudge** [comment]
Duplicate of #12
