### ISSUE TITLE
Does not work on Visual Studio 2019 Professional

### ISSUE THREAD

**Issue by dbarasch** [natanfudge/Auto-Using#14]
I can't seem to install the extension using Visual Studio 2019.  Here is the log generated.

7/7/2019 10:21:18 AM - Microsoft VSIX Installer
7/7/2019 10:21:18 AM - -------------------------------------------
7/7/2019 10:21:18 AM - vsixinstaller.exe version:
7/7/2019 10:21:18 AM - 16.1.3132
7/7/2019 10:21:18 AM - -------------------------------------------
7/7/2019 10:21:18 AM - Command line parameters:
7/7/2019 10:21:18 AM - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,C:\Users\aBar\Downloads\Fudge.auto-using-0.7.9.vsix
7/7/2019 10:21:18 AM - -------------------------------------------
7/7/2019 10:21:18 AM - Microsoft VSIX Installer
7/7/2019 10:21:18 AM - -------------------------------------------
7/7/2019 10:21:19 AM - Initializing Install...
7/7/2019 10:21:19 AM - Extension Details...
7/7/2019 10:21:19 AM - 	Identifier         : auto-using
7/7/2019 10:21:19 AM - 	Name               : Auto-Using for C#
7/7/2019 10:21:19 AM - 	Author             : Fudge
7/7/2019 10:21:19 AM - 	Version            : 0.7.9
7/7/2019 10:21:19 AM - 	Description        : Provides intellisense for and imports references from all available sources.
7/7/2019 10:21:19 AM - 	Locale             : en-US
7/7/2019 10:21:19 AM - 	MoreInfoURL        : 
7/7/2019 10:21:19 AM - 	InstalledByMSI     : False
7/7/2019 10:21:19 AM - 	SupportedFrameworkVersionRange : [0.0,2147483647.2147483647]
7/7/2019 10:21:19 AM - 
7/7/2019 10:21:19 AM - 	SignatureState     : Unsigned
7/7/2019 10:21:19 AM - 	Supported Products : 
7/7/2019 10:21:19 AM - 		Microsoft.VisualStudio.Code
7/7/2019 10:21:19 AM - 			Version : 
7/7/2019 10:21:19 AM - 
7/7/2019 10:21:19 AM - 	References         : 
7/7/2019 10:21:19 AM - Signature Details...
7/7/2019 10:21:19 AM - 	Extension is not signed.
7/7/2019 10:21:19 AM - 
7/7/2019 10:21:19 AM - Searching for applicable products...
7/7/2019 10:21:19 AM - Found installed product - Global Location
7/7/2019 10:21:19 AM - Found installed product - Visual Studio Professional 2019
7/7/2019 10:21:19 AM - Found installed product - Visual Studio Build Tools 2019 (2)
7/7/2019 10:21:19 AM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)

**Comment by natanfudge** [comment]
Hey, this is a VSCode extension, not a Visual Studio extension. This feature is already built-in visual studio, unfortunately microsoft were not kind enough to turn it on by default, it seems. You can toggle this option on/off by navigating to Tools > Options > Text Editor > C# > IntelliSense.
