### ISSUE TITLE
fails to activate after installating

### ISSUE THREAD

**Issue by habsfanongit** [natanfudge/Auto-Using#18]
Hi,
it looks like Microsoft's changing C# extension publisher name from ms-vscode to ms-dotnettools broke this extension.
after installing the extension and restarting VsCode, you get the following error
"Cannot activate the 'Auto-Using for C#' extension because it depends on an unknown 'ms-vscode.csharp' extension ."
I only tested on MAC but suspect the same will happen in Windows and Linux as well.

**Comment by natanfudge** [comment]
duplicate of #19
