### ISSUE TITLE
The C# Extension had Changed ms-vscode.csharp to dotnettools.charp......

### ISSUE THREAD

**Issue by DonPangPang** [natanfudge/Auto-Using#19]
So, There's going to be a dependency problem...

**Comment by natanfudge** [comment]
I assumed the C# extension would implement Auto-Using itself by now (https://github.com/OmniSharp/omnisharp-roslyn/issues/1482), but I guess not. I'll re-setup the workspace so I can push #17 .

**Comment by natanfudge** [comment]
It should be fixed now.
