### ISSUE TITLE
Feature Request: explicit addition of using statement

### ISSUE THREAD

**Issue by gsscoder** [natanfudge/Auto-Using#26]
**First of all thank for your project and for sharing it!**
I would like to right click an unresolved symbol and be able to explicitly add its _using statement_.

It would be great!

Thank you,
Giacomo S. S.

**Comment by natanfudge** [comment]
You can do this by pressing `ctrl+.` by default I believe, is that good enough?

**Comment by koi-hime** [comment]
> You can do this by pressing `ctrl+.` by default I believe, is that good enough?

Works good enough for me!
