### ISSUE TITLE
add new file  then can't auto-

### ISSUE THREAD

**Issue by zelinDavid** [natanfudge/Auto-Using#8]
Hi，the extension is very good,  but I found something wrong that when I add new file, vscode will 
never snippet words again. see picture below.
at first, I type File, then it works well.
![image](https://user-images.githubusercontent.com/16894134/55945013-7af3aa00-5c7c-11e9-96af-ba5ed439b51e.png)

but after I add new file by: ctrl+n, ctrl+s, save file by xx.cs.
then I just type something but never show snippet again.

![image](https://user-images.githubusercontent.com/16894134/55945609-b80c6c00-5c7d-11e9-9785-ad309a8c8f83.png)

I'm almost sure it have relation to the Auto-Using for I deleted the extension, and doing the same operations(add new file by: ctrl+n, ctrl+s, save file by xx.cs and type). some snippets shows.

hope Auto-Using  better and better, it's useful.
thanks.

vscode Info:
Version: 1.33.0 (system setup)
Commit: 0dd516dd412d42323fc3464531b1c715d51c4c1a
Date: 2019-04-04T15:14:28.026Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.16299

**Comment by natanfudge** [comment]
Hey David, thanks for the bug report. 
I fixed the issue. You should see [a new version of Auto-Using in the marketplace](https://marketplace.visualstudio.com/itemdetails?itemName=Fudge.auto-using) that fixes this bug in a few seconds. 
Please tell me if you have any more issues.

**Comment by zelinDavid** [comment]
Wow，that's great. It took me near an hour  locating the question. haha. thank you for your contributing

**Comment by natanfudge** [comment]
No problem!
